### PR TITLE
LMS Front End Fixes

### LINKED ISSUE #351: LMS Front End bugs
- [x] Checkbox when create punishment
- [x] Useless button in marks journal
- [x] Handle resetting form in profile page

### PR DESCRIPTION
**Pull request by askatsevalov**
Closes #351

### CODE REVIEW

File: front-end/src/components/Marks/Marks.vue [hunk 1]
```diff
@@ -294,18 +294,18 @@
       </span>
     </el-dialog>
 
-    <el-drawer :title="drawerTitle" :visible.sync="drawer" direction="rtl">
+    <!-- <el-drawer :title="drawerTitle" :visible.sync="drawer" direction="rtl">
```
Comment (vmloskutov) [inline front-end/src/components/Marks/Marks.vue:297]: pls remove, don't comment

File: front-end/src/components/Discipline/Punishment/Punishment.vue [hunk 2]
```diff
@@ -500,6 +502,7 @@ export default {
       });
     },
     onRemovePunishmentCheckboxClick() {
+      console.log(this.editPunishment);
```
Comment (vmloskutov) [inline front-end/src/components/Discipline/Punishment/Punishment.vue:505]: pls remove

File: front-end/src/components/Discipline/Punishment/Punishment.vue [hunk 3]
```diff
@@ -411,7 +411,9 @@ export default {
         student: null,
         teacher: null,
         date: moment().format("YYYY-MM-DD"),
+        remove_date: null,
       };
+      console.log("zhopa", this.editPunishment);
```
Comment (vmloskutov) [inline front-end/src/components/Discipline/Punishment/Punishment.vue:416]: pls remove

**Review by vmloskutov — APPROVED** [review]

**Review by vmloskutov — APPROVED** [review]
